#.travis.yml
sudo: required
dist: trusty

language: node_js
node_js:
  - "8.2"

branches:
  only:
    - master
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
 
before_script:
  - npm install -g yargs
  - npm install -g dotenv
  - npm install -g firebase-tools
  - npm install -g @angular/cli


script:
  - npm run test:ci
# dont use until e2e:ci is fixed
#  - npm run e2e:ci
  - npm run build

#turn off for now
after_success:
 - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change